func foo(){ //this should cause an error

}